### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by forestuser** [artefactual-labs/docker-gearmand#10]
Hello. When creating a pod + service, gearmand stops working.

LOG
INFO 2021-09-03 04:46:16.396362 [ main ] Initializing Gear on port tcp://10.101.82.102:4730 with SSL: false
INFO 2021-09-03 04:46:16.000000 [ main ] Starting up with pid 1, verbose is set to INFO
ERROR 2021-09-03 04:46:16.000000 [ main ] 0.0.0.0:tcp://10.101.82.102:4730 getaddrinfo(Unrecognized service) -> libgearman-server/gearmand.cc:626
INFO 2021-09-03 04:46:16.000000 [ main ] Shutdown complete

  containers:
  - name: gearmand
    image: artefactual/gearmand:latest
    args:
    - --listen=0.0.0.0
    - --port=4730
    ports:
    - containerPort: 4730

If you deploy the pod, and deploy the service after germand initialization. Then germand works.
If you deploy pod and service together, an error occurs and gearmand goes into shutdown.

**Comment by esabol** [comment]
I think these issues are related:

https://github.com/kubernetes/kubernetes/issues/76790
https://github.com/alpinelinux/docker-alpine/issues/149

What do you think, @sevein and/or @Mararok ?

**Comment by sevein** [comment]
I can't help you because I'm not using k8s, but I'd be happy to accept pull requests. Is this something that we can mitigate from our entry point?
