### ISSUE TITLE
Update https://hub.docker.com/r/artefactual/gearmand/ with 1.1.19.1

### ISSUE THREAD

**Issue by esabol** [artefactual-labs/docker-gearmand#11]
Hi. https://hub.docker.com/r/artefactual/gearmand/ says `latest` is 1.1.18, but that seems to be incorrect. The `artefactual/gearmand:latest` image contains gearmand 1.1.19.1 (or so I've been told). I think https://hub.docker.com/r/artefactual/gearmand/ needs to be updated? I'm specifically referring to the "Supported tags and respective Dockerfile links" section of the overview.

**Comment by sevein** [comment]
Thank you, @esabol. It looks like Docker Hub disabled README sync when automated builds are disabled.

> If automated build is enabled, readme will be synced from the source code repository on successful build.

I've uploaded the README document manually. I don't think this repo for their open source program unfortunately.

**Comment by esabol** [comment]
@sevein : It looks like the Docker Hub README needs to be updated to reflect the new image tags again.

Thanks for updating your repository for the new gearmand releases.

**Comment by sevein** [comment]
Thanks! I'm now buliding 1.1.20.1 and 1.1.21.1, not published yet.
Using qemu emulation to build the arm64 target, it takes forever!
