### ISSUE TITLE
QUEUE_ERROR:QUEUE_ERROR -> libgearman/client.cc:1603

### ISSUE THREAD

**Issue by bilua-xiaolei** [artefactual-labs/docker-gearmand#12]
I got this error from my application and checking gearmand logs (on debug mode), I found this error:

```
mysql_stmt_execute failed: Unknown prepared statement handler (1)
```

Looks like if you use the mysql driver, is needed the uuid package (libuuid in alpine)

As I'm not sure if this repository is maintained any more, if you get this error, just create your own Dockerfile and add these thre lines:

```
USER root
RUN apk add libuuid
USER gearman
```

source: https://ma.ttias.be/gearman-queue-error-mysql_stmt_execute-failed-unknown-prepared-statement-handler-1/

**Comment by sevein** [comment]
Thank you! If you are interested, please feel submit a pull request.
