### ISSUE TITLE
Container is not starting in kubernetes 

### ISSUE THREAD

**Issue by ananta-code** [artefactual-labs/docker-gearmand#14]
Hi while starting the container in kubernetes i am getting error .
INFO 2023-02-20 11:54:06.040737 [  main ] Initializing Gear on port tcp://100.112.19.203:4730 with SSL: false
   INFO 2023-02-20 11:54:06.000000 [  main ] Starting up with pid 1, verbose is set to INFO
  ERROR 2023-02-20 11:54:06.000000 [  main ] 0.0.0.0:tcp://100.112.19.203:4730 getaddrinfo(Unrecognized service) -> libgearman-server/gearmand.cc:626
   INFO 2023-02-20 11:54:06.000000 [  main ] Shutdown complete
Please suggest what is the issue?

**Comment by jraddaoui** [comment]
Hi @ananta-code, https://github.com/artefactual-labs/docker-gearmand/issues/10 seems to be the same issue and it includes a couple of suggestions to solve it.

**Comment by ananta-code** [comment]
Also after starting the pod i configured the gearman plugin in my jenkins and the connection is working perfectly fine but when i trigger jobs i can still see the job queue in gearman queue.
Is there any additional configuration i have to do to view the job queue in gearman ?
