### ISSUE TITLE
Support mysql backend

### ISSUE THREAD

**Issue by Mararok** [artefactual-labs/docker-gearmand#2]
Hey, can you add support for mysql queue backend ? Now im doing it myself :(

I added install ```mariadb-dev``` package and ```--with-mysql=yes```, container started and created table and running.
You can check details on(I removed redis support from my image - it need compatible check) https://github.com/SAREhub/Servitiom/tree/first_version/gearmand and https://github.com/SAREhub/Servitiom/blob/first_version/bin/test/gearmand/deploy.sh

Now Im adding support for docker secretes for MYSQL_PASSWORD

**Comment by sevein** [comment]
I can definitely try! Thanks.

**Comment by Mararok** [comment]
I updated my local version
- added back redis support
- added MYSQL_PASSWORD secret support
- installed bash(used for ${!var} indirect expansion)
It will be great if i can use your image with mysql support in my project :)

**Comment by sevein** [comment]
@Mararok see #5, please!
